// Sample video data for the assignment
export const videos = [
  {
    id: "1",
    title: "Learn React in 30 Minutes",
    thumbnail: "https://picsum.photos/320/180?random=1",
    channelName: "Code Academy",
    views: "1.2M views",
    category: "Coding",
  },
  {
    id: "2",
    title: "Top 10 Gaming Moments 2024",
    thumbnail: "https://picsum.photos/320/180?random=2",
    channelName: "Game Zone",
    views: "850K views",
    category: "Gaming",
  },
  {
    id: "3",
    title: "Relaxing Music for Study",
    thumbnail: "https://picsum.photos/320/180?random=3",
    channelName: "Chill Beats",
    views: "3.5M views",
    category: "Music",
  },
  {
    id: "4",
    title: "Breaking News Today",
    thumbnail: "https://picsum.photos/320/180?random=4",
    channelName: "Daily News",
    views: "500K views",
    category: "News",
  },
  {
    id: "5",
    title: "Football Highlights - Best Goals",
    thumbnail: "https://picsum.photos/320/180?random=5",
    channelName: "Sports Hub",
    views: "2.1M views",
    category: "Sports",
  },
  {
    id: "6",
    title: "JavaScript Basics for Beginners",
    thumbnail: "https://picsum.photos/320/180?random=6",
    channelName: "Dev Tutorials",
    views: "920K views",
    category: "Coding",
  },
  {
    id: "7",
    title: "Epic Battle Royale Gameplay",
    thumbnail: "https://picsum.photos/320/180?random=7",
    channelName: "Pro Gamer",
    views: "1.8M views",
    category: "Gaming",
  },
  {
    id: "8",
    title: "Morning News Roundup",
    thumbnail: "https://picsum.photos/320/180?random=8",
    channelName: "World Today",
    views: "320K views",
    category: "News",
  },
  {
    id: "9",
    title: "Best Workout Music Mix",
    thumbnail: "https://picsum.photos/320/180?random=9",
    channelName: "Fitness Beats",
    views: "1.5M views",
    category: "Music",
  },
  {
    id: "10",
    title: "Cricket Match Highlights",
    thumbnail: "https://picsum.photos/320/180?random=10",
    channelName: "Sports Live",
    views: "4.2M views",
    category: "Sports",
  },
  {
    id: "11",
    title: "Build a Todo App with React",
    thumbnail: "https://picsum.photos/320/180?random=11",
    channelName: "React Masters",
    views: "650K views",
    category: "Coding",
  },
  {
    id: "12",
    title: "Acoustic Guitar Covers",
    thumbnail: "https://picsum.photos/320/180?random=12",
    channelName: "Music Lounge",
    views: "780K views",
    category: "Music",
  },
];
